
const idoPoolsTest = [
  {
    poolId: 0,
    name: 'test Project 1',
    nameKey: 'test1',
    chainId: 97,
    type: 'IGO',
    distribution: 'Claim',
    avatar: 'https://bafkreig6d5rnrdd5hi46xikjry5hb5tg2oxxmdwfseisumqyjag5ldxtiu.ipfs.dweb.link/',
    subName: '$VIP',
    claimStarts: 0,
    idoTokenPrice: 0.15,
    launchTime: 1640939561000,
    vesting: '10% unlocked 7 days after IDO, then weekly vesting for 12 months (airdrop method)',
  },
  {
    poolId: 1,
    name: 'test Project 2',
    nameKey: 'test2',
    chainId: 97,
    type: 'IGO',
    distribution: 'Claim',
    avatar: 'https://bafkreig6d5rnrdd5hi46xikjry5hb5tg2oxxmdwfseisumqyjag5ldxtiu.ipfs.dweb.link/',
    subName: '$VIP',
    claimStarts: 1640939561000,
    idoTokenPrice: 0.047,
    launchTime: 1640939561000,
    vesting: '10% unlocked 7 days after IDO, then weekly vesting for 12 months (airdrop method)',
  },
]
export const IdoPoolsLocal = idoPoolsTest

export const IdoDefaultData = {
  "name": "--",
  "nameKey": "TFI",
  "chainId": 56,
  "type": "IGO",
  "distribution": "Airdrop",
  "avatar": "/logo2.png",
  "subName": "$TFI",
  "claimStarts": 0,
  "idoTokenPrice": 0,
  "launchTime": 1643119200000,
  "vesting": "10% unlocked 7 days after IDO, then weekly vesting for 12 months (airdrop method)",
  "claimRatio": 0.66,
  "description": "--",
  "about": "--",
  "idoType": "IDO",
  "pic1": "/images/logo.png",
  "pic2": "/images/logo.png",
  "pic3": "/images/logo.png",
  "pic4": "/images/logo.png",
  "pic5": "/images/logo.png",
  "website": "https://launchpad.trustfi.org/",
  "twitter": "https://twitter.com/",
  "telegram": "https://t.me/",
  "chainName": "BSC",
  "startTime": "01/25/2022 UTC",
  "endTime": "01/25/2022 UTC",
  "idoTokenSymbol":"FOTA",
  "idoOnChainName":"BSC",
  "idoOnChainLogo":"https://trustfi.s3.ap-southeast-1.amazonaws.com/images/fota.png",
  "distributedName":"SOLANA",
  "distributedLogo":"https://trustfi.s3.ap-southeast-1.amazonaws.com/images/fota.png"
}